try {
    hello();
}
catch(err){
    throw "define hello function!";
}
finally{
    console.log("finally!");
}